'use client'

interface AIDisclaimerProps {
  /** 'full' = the complete sentence, for app screens.
   *  'short' = the one-line version, for PDF footers and email footers. */
  variant?: 'full' | 'short'
  className?: string
}

export default function AIDisclaimer({ variant = 'full', className = '' }: AIDisclaimerProps) {
  if (variant === 'short') {
    return (
      <p className={`text-xs text-gray-400 ${className}`}>
        AI-generated for information only — not legal or professional advice. Verify before acting.
      </p>
    )
  }

  return (
    <div
      className={`rounded-md border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-600 ${className}`}
    >
      <span className="font-medium text-gray-700">CompliBoard is an information tool, not professional advice.</span>{' '}
      Its reports and checklists are generated by AI using current regulatory sources, and AI can make
      mistakes. Verify important items against the cited source or with a qualified professional before
      acting on them.
    </div>
  )
}
