export const INDUSTRY_FOLDERS: Record<string, string[]> = {
  'chemical-manufacturing': [
    'OSHA Safety',
    'SDS Sheets',
    'Environmental',
    'Shipping & Transport',
    'Permits & Licenses',
    'Training Records',
    'Inspection Reports',
    'Emergency Plans',
    'Waste Management',
  ],
  'restaurant': [
    'Food Safety',
    'Health Permits',
    'Alcohol License',
    'OSHA Safety',
    'Training Records',
    'Inspection Reports',
    'HR Documents',
  ],
  'food-beverage-manufacturing': [
    'Food Safety (FSMA/HACCP)',
    'OSHA Safety',
    'Environmental',
    'Permits & Licenses',
    'Training Records',
    'Inspection Reports',
    'Supplier Records',
  ],
  'cannabis': [
    'License & Permits',
    'Inventory Records',
    'OSHA Safety',
    'Pesticide Records',
    'Training Records',
    'Inspection Reports',
    'Security Plans',
  ],
  'auto-body-dry-cleaners': [
    'Hazardous Waste',
    'Air Quality',
    'OSHA Safety',
    'Permits & Licenses',
    'Training Records',
    'Inspection Reports',
    'Chemical Inventory',
  ],
  'wood-products-sawmills': [
    'OSHA Machinery Safety',
    'Air Quality',
    'Shipping & Transport',
    'Permits & Licenses',
    'Training Records',
    'Inspection Reports',
    'Equipment Records',
  ],
  'construction': [
    'OSHA Safety',
    'Permits & Licenses',
    'Training Records',
    'Inspection Reports',
    'Contracts',
    'Equipment Records',
    'HR Documents',
  ],
  'healthcare': [
    'HIPAA Compliance',
    'Licenses & Certifications',
    'OSHA Safety',
    'Training Records',
    'Inspection Reports',
    'HR Documents',
    'Insurance',
    'Patient Safety',
    'Infection Control',
  ],
  'hospice': [
    'CMS Compliance',
    'Licenses & Certifications',
    'HIPAA Compliance',
    'OSHA Safety',
    'Training Records',
    'Inspection Reports',
    'HR Documents',
    'Insurance',
    'Patient Safety',
    'Infection Control',
    'Emergency Plans',
  ],
  'other': [
    'OSHA Safety',
    'Permits & Licenses',
    'Training Records',
    'Inspection Reports',
    'HR Documents',
    'General Documents',
  ],
}

export function getFolders(industry: string): string[] {
  return INDUSTRY_FOLDERS[industry] || INDUSTRY_FOLDERS['other']
}
