-- ============================================================
-- COMPLIBOARD — MIGRATION 001: THE SPINE  *** SUPERSEDED BY 000. NOW A NO-OP. ***
-- ============================================================
--
-- WHAT THIS FILE USED TO DO
--
-- Written 18 July 2026, it created the six Requirements tables — requirement_templates,
-- entities, obligations, obligation_evidence, corrections, agencies — with eight indexes,
-- RLS on all six, and six policies. It was applied to production and to staging, by hand,
-- long before there was a migration runner.
--
-- WHY IT IS EMPTY NOW
--
-- `000_baseline.sql` was written on 9 September by reading production's catalogs and
-- reconstructing the DDL from them. Production had 001 applied at that moment, so
-- **everything 001 creates is already inside 000** — all 6 tables, all 8 indexes, RLS on
-- all 6, all 6 policies. Verified against a database with only 000 applied: 6 of 6, 8 of
-- 8, 6 of 6, 6 of 6.
--
-- That redundancy was invisible for as long as nobody ran the chain from an empty
-- database, because 001 had been marked as applied by hand before 000 was ever written.
-- The history said "already done" and the file was never executed again.
--
-- *** IT BROKE THE FIRST TIME THE CHAIN WAS RUN FROM ZERO, 11 SEPTEMBER. ***
--
--     ERROR: relation "requirement_templates" already exists (SQLSTATE 42P07)
--
-- 000 uses `create table if not exists`; this file used bare `create table`. So 000 made
-- the tables and 001 fell over them. **The chain has never once been able to build a
-- database from nothing** — which is exactly the thing TODO 1.3 exists to prove, and
-- exactly the reason it is worth proving rather than assuming.
--
-- WHY THIS IS A NO-OP RATHER THAN A DELETED FILE
--
-- Deleting it would renumber nothing but would leave a gap that invites the question
-- "what was 001, and did we lose something?" every time someone reads the directory. It
-- would also mean the two databases that already record 001 as applied disagree with the
-- files on disk. An empty file with its history written down costs one read and answers
-- the question permanently.
--
-- The original 187 lines are in git history at commit c830700 and earlier. Nothing is lost.
--
-- *** THE RULE THIS ESTABLISHES, WHICH IS THE VALUABLE PART: ***
-- A migration chain that has only ever been applied incrementally is not known to work.
-- It is only known to have worked, once, in one order, against one starting state. Run it
-- from zero, or do not claim it reproduces anything.
-- ============================================================

-- Intentionally empty. See above.
select 1 where false;
